### ISSUE TITLE
Intepret Cache Headers

### ISSUE THREAD

**Issue by hawx** [hawx/riviera#11]
When requesting a feed the feed may specify how often to fetch the feed. But it may also return `Expires` or `ETag` headers:
- If an `Expires` header is returned, then if that date is further in the future than the next fetch time it should be used instead.
- If an `ETag` header is returned send an `If-None-Match` header with the given value on the next fetch.

And, always send a `If-Modified-Since` with the last fetch time.

Ignore `Cache-Control` for now, it will probably be more hassle than it's worth.

### Tasks

- [x] Always send `If-Modified-Since` with the last fetch time.
- [ ] If an `Expires` header is returned then set the next fetch time to the maximum of it or the usual value.
- [x] If an `ETag` header is returned send an `If-None-Match` header with the next fetch.
